apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bcp-parser
  namespace: bcp-parser
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
spec:
  ingressClassName: nginx
  rules:
    - host: bcp-parser.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: bcp-frontend
                port:
                  number: 80
